components:
  schemas:
    '#PersonBirth':
      properties:
        birthDate:
          description: The year, month, and day on which a person was born.
          example: 2000-01-01 00:00:00
          format: YYYY-MM-DD
          type: date
      required:
      - birthDate
      type: object
    '#PersonContact':
      properties:
        email:
          description: The numbers, letters, and symbols used to identify an electronic
            mail (e-mail) user within the network to which the person or organization
            belongs.
          example: user@example.com
          format: email
          type: string
        emailAddressType:
          description: The type of electronic mail (e-mail) address listed for a person
            or organization.
          example: Work
          format: email
          type: string
      required:
      - email
      - emailAddressType
      type: object
    '#PersonName':
      properties:
        firstName:
          description: The first name of a person or individual, further defined by
            nameType.
          example: John
          format: name
          type: string
        lastName:
          description: The last name of a person, further defined using nameType.
          example: Smith
          format: name
          type: string
        nameType:
          description: The types of names given for a person
          example: Given
          format: name
          type: string
      required:
      - firstName
      - lastName
      - nameType
      type: object
info:
  description: OpenAPI Spec
  title: Machine-Readable Schema for Person
  version: 1.0.0
openapi: 3.0.0
paths: {}
